### ISSUE TITLE
Something doesn't seem right

### ISSUE THREAD

**Issue by MaymonAdir** [NemesisSSBU/Playable_Bosses#1]
When I installed this mod, the game crashes. Can someone help me with this?

**Comment by MaymonAdir** [comment]
@NemesisSSBU I need your help

**Comment by NemesisSSBU** [comment]
Did [RPTOR914](https://github.com/NemesisSSBU/Playable_Bosses/issues?q=is%3Aissue+is%3Aopen+author%3ARPTOR914) fix your issue @MaymonAdir?
