### ISSUE TITLE
Is it possible to have multiple people play as the same boss? [Possible Feature in the Future]

### ISSUE THREAD

**Issue by cheetahsbdf** [NemesisSSBU/Playable_Bosses#10]
Being able to play as the same boss with multiple people would seem like a cool idea. I hope this can be done in the future! The idea is simply two or more people being able to play as master hand, crazy hand, etc.

**Comment by NemesisSSBU** [comment]
This does seem like a good idea but unfortunately the way this mod is programmed is where only one specific boss can be spawned in at a single time. If two of the same bosses spawn in, they're all referencing the same mod file and it creates some really wonky scenarios.

I wish me and GamerSubzero would've thought of it earlier on like how Claude did with his mod but I think for now this will have to unfortunately remain, but thank you for the suggestion.
