### ISSUE TITLE
WOL Bosses do not appear after unlocking Mario

### ISSUE THREAD

**Issue by zm1868179** [NemesisSSBU/Playable_Bosses#11]
I updated to the newest release started a new WOL Save and unlocked mario but when going to the CSS Screen there is only Kirby and Mario no Bosses appear at all.

**Comment by NemesisSSBU** [comment]
You're totally right!

I just tested this and I accidently put save_no to 1 which is actually someone else (I'd assume Donkey Kong but I haven't tested too far on this new save file). What I should've done is put it to save_no 0, which is actually Mario. Total fail on my part and I apologize for that.

A new update should be out in a couple of hours that truly fixes this issue, thank you for downloading the mod.

**Comment by NemesisSSBU** [comment]
This issue should be fully resolved but just in case, let me know if any other issues arise while playing.

**Comment by cheetahsbdf** [comment]
I figured out the problem. It seems that changing the msg-name.msbt caused these bosses to not spawn for me. It works great now, Thanks for the attentiveness. I do have another question though. How would I go about adding more "npc's/bosses" I want to add sandbag for the fun, but when I edit the lib.rs to include him as a unique css slot and change the item_kind to spawn Sandbag, it's still mario. I have no experience with this type of code so I simply copied one boss mod file and renamed it to another entity. Could you teach me how to set that up correctly? I have no plan on distributing it, I just want it for personal use.
