### ISSUE TITLE
WOL Crashes

### ISSUE THREAD

**Issue by zm1868179** [NemesisSSBU/Playable_Bosses#13]
It seems most bosses cause the game to crash even when using giga bowser when trying to go through WOL

Back before these mods exists, I did memory editing to swap in giga bowser and he was fully playable on all fights in WOL. With the MOD it seems even with him it crashes upon loading most fights.

Not sure if this can be fixed but it does seem to be an issue without mods enabled with a save file that had giga bowser selected before disabling the mode the game works fine with him.

**Comment by NemesisSSBU** [comment]
Strange about Giga Bowser crashing the game. The only thing I can think of is if you lost in an HP battle as Giga Bowser, that would crash the game regardless of mods.

The only way I was able to crash the game within WOL besides losing as Giga Bowser in an HP battle would be switching to Dharkon or Galeem and starting a battle, which of course isn’t supposed to happen but I believe I know what might be causing this issue with them. 

I’ve tried with all other bosses and no issues occurred with them but just a quick question: who were the bosses you chose the crashed the game?

Thank you for downloading the mod and reporting this issue.

**Comment by zm1868179** [comment]
I've tried loading the game with master hand or wol master hand. They will load into the map and if I move to a sprit and start the battle the press start screen appears and pressing the + button to start the battle the game will start to load the loading icon freezes then the game crashes.

If I reload the game and go right back into the save and try to start a match on WOL same thing starts to load the icon freezes then the game crashes.

I was able to get one match to start and completed it but going to the next match on the map same thing would happen at the load screen freeze then crash.

Giga Bowser I think was a fluke as it only crashed one time after reloading the game no issues happened I was able to go into battles so far without a crash.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zm1868179** [comment]
I just erased the contents of my ultimate folder and atmosphere folder and copied over only the files from the current release. I loaded up my Save file right after unlocking Mario in WOL which unlocked the bosses and went to the first fight right after Mario (The Guardian) with WOL Master hand selected and tried to do that fight. Freeze on loading and crash.

These where attempted on Guardian Spirit Right after Mario unlock in WOL:

Just reloaded the game and attempted with the following bosses:
Attempted to do Guardian Sprit fight right after Mario unlock in WOL.

WOL Master Hand (Loading Freeze then Crash)
Master Hand (Loading Freeze then Crash)
Crazy Hand (Battle Will load and I can complete it)

These Where performed on a Character Battle (Villager Specifically right after Guardian Spirit):

Dharkon (Battle Will attempt to load then game crashes Gets farther than master hand I hear the item equip sound then crashes)
Gallem (Same as Dharkon) 
Marx (Works loads into Character Battle)

(These were Switched via quit in character battle with a working character and choosing change party did not exit back to main map)
Ganon (Works Loads into Character Battle)
Dracula (Works Loads into Character Battle)
Galleom (Works Loads into Character Battle)
Rathalos (Works Loads into Character Battle)
WOL Master Hand (Works Loads into Character Battle)
Master Hand (Works Loads into Character Battle)
Dharkon (Battle Will attempt to load then game crashes Gets farther than master hand I hear the item equip sound then crashes)
Gallem (Same as Dharkon) 

Its almost as if Master Hand and WOL Master hand will crash when trying to enter a spirit Battle but will load just fine in a character battle While Other Bosses with the exception of Gallem and Dharkon which don't seem to load in anything but the overworld map Sprit or character battles seem to crash if trying either one of them.

**Comment by NemesisSSBU** [comment]
I was able to successfully replicate the issue and I believe successfully fix it!

An update to fix this issue and some more will be released in a couple of hours.

Be sure to let us know if anymore issues arise and let us know if this issue is fully fixed on your end.
