### ISSUE TITLE
Move list pages (Enhancement request) 

### ISSUE THREAD

**Issue by zm1868179** [NemesisSSBU/Playable_Bosses#15]
Back when Claude was working on this mod there was a time when he managed to add custom move lists pages for the bosses into the pause menu move list pages that shows the moves of all the characters. Would it be possible to have this return for the bosses or at-least in the meantime have a move list added to the readme document to help players know how to execute the moves for the bosses?

**Comment by NemesisSSBU** [comment]
I think this is a really good idea. I’ll look into how to go about implementing this like how Claude did in order to provide newer users of the mod with move set information.

**Comment by NemesisSSBU** [comment]
Your request has been implemented in the [latest update](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/0.9.8.3)
