### ISSUE TITLE
Dracula Move Issue

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#16]
Hello, I noticed that the second style of dracula when he makes the attack where he puts his fist on the ground dracula freezes and can no longer move and remains stationary in that position. Please fix this

**Comment by NemesisSSBU** [comment]
This does typically happen on non-fully flat maps. I’ll be looking into this shortly; thank you for reporting.

**Comment by NemesisSSBU** [comment]
Thank you for reporting this issue and it has now been fixed in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/0.9.9)!
