### ISSUE TITLE
When galleom and ganon die they don't do the animation of death

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#17]
Hello, sorry for the new issue but I wanted to tell you that when galleom and ganon die they remain still without doing the animation of death and fall for the sky. Please fix this bug

**Comment by NemesisSSBU** [comment]
We’re currently working on a massive bug patch and this almost slipped by us. Thank you for reporting this issue and it should be fixed by the next update (within a few hours or a day).

**Comment by NemesisSSBU** [comment]
This issue is fixed in the [latest version](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/0.9.9.1) of the mod! Thank you for reporting the issue!
