### ISSUE TITLE
Please make the bosses can regenerated

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#18]
Please put that the bosses can regenerate because then it is not much fun that they all have a life. Do as Claude1308 that when a boss dies he regenerates. Please

**Comment by NemesisSSBU** [comment]
The thing is, from the moment we started development of this mod, we wanted to treat bosses as if you're truly playing as bosses. Unfortunately we took this to the extreme and with that we kept the 1-life aspect of the bosses for a couple of years. In those years we designed all the game modes that these bosses and the 1-life aspect is so deeply engraved into the code, it would require an almost complete rewrite of how bosses are spawned in.

In a way, I like the 1-life aspect of the mod as it shows how bosses are meant to be a brute force that once defeated, the pressure is relieved on the opponent; just like how you would feel when facing a real SSBU boss.
