### ISSUE TITLE
Peach's Final Smash Causes the Bosses to Disappear

### ISSUE THREAD

**Issue by 3ngZl** [NemesisSSBU/Playable_Bosses#19]
Apparently after Peach uses her Final Smash the Bosses just are gone. The camera doesn't lock on to them, their hitboxes are gone and the game still counts them as alive. So I guess they despawn.

**Comment by NemesisSSBU** [comment]
Huh. I’ll look into this, thank you for reporting!

**Comment by NemesisSSBU** [comment]
This issue has now been resolved in the [latest update](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0-BETA).
