### ISSUE TITLE
Team Battle Issues

### ISSUE THREAD

**Issue by 3ngZl** [NemesisSSBU/Playable_Bosses#21]
So team battle (with stocks) seems to be kind of broken sometimes, from the cpu bosses restocking causing soflocks or even a crash one time. Sometimes the battle just doesn't end, Specifically, I was fighting Marx +2 others on the opposite team, and after everyone on Marx's team was defeated the battle didn't end.

**Comment by NemesisSSBU** [comment]
Thank you for reporting this issue. After some investigation we believe to have found and fixed this issue. This fix will be available in the full release.

**Comment by NemesisSSBU** [comment]
This is issue has been fixed in the [full release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)
