### ISSUE TITLE
Issues That I haven't fixed yet for V1.0.0

### ISSUE THREAD

**Issue by NemesisSSBU** [NemesisSSBU/Playable_Bosses#25]
# This is more of a personal note so I remember what's left to fix before I release the code edits and full version.

Current WIP fixes:

None! ⭐

Current Fixed issues (Changes since Beta): 

- Reworked Master Hand and Crazy Hand's code - 🟢 
- Master Hand and Crazy Hand have updated team moves (only when they are on the same team and facing the correct way) (Jump button on Crazy Hand = team punch, Jump button on Master Hand = stage shock, DPAD UP on Master Hand = bark attack, DPAD UP on Crazy Hand = laser duet, DPAD DOWN on Master Hand = Scratch Attack) - 🟢 
- Master Hand and Crazy Hand's AI now initiate their team moves on their own (only when they are on the same team and facing the correct way) - 🟢 
- Master Hand and Crazy Hand's death animations can be facing the wrong direction during death - 🟢
- Master Hand and Crazy Hand now have different spawn in animations depending on if they're on the same team or independent. - 🟢 
- Dharkon and Galeem's inputs now properly disable until they are within the idle animation - 🟢 
- Dharkon and Galeem both have their "vanish" ability removed as to not create extremely unfair situations - 🟢 
- Dharkon and Galeem have different targeting flags for CPU fighters - 🟢 
- Dharkon and Galeem no longer have sped up animations - 🟢 
- Dharkon and Galeem have had their AI random wait times adjusted to become more unrelenting (shorter, is 59 random, was 200 random) - 🟢 
- The issue involving when Dharkon or Galeem dies, and their counterpart exists, either one, depending on fighter ENTRY_ID, get’s locked in place for the remainder of the game and cannot take damage, has been fixed - 🟢 
- Dharkon and Galeem’s invisible Master Hand can no longer be stunned - 🟢  
- Better CPU Targeting of Dharkon and Galeem - 🟢 
- Flying bosses now start off with an invisible falling animation on the fighter’s side rather than being put into standby - 🟢 
- Flying bosses (except Rathalos) now have a more "floaty" feel when controlling their movement - 🟢 
- Master Hand and Crazy Hand position oriented attacks now go by distance from the ground for better functionality - 🟢
- Crazy Hand’s Fire Chariot attack no longer gets stuck infinitely on uneven surfaces - 🟢 
- Ganon has a new move on the down DPAD button - 🟢 
- Ganon has a new move on the left DPAD button - 🟢 
- Ganon have a new double thunder attack on the down Attack button - 🟢
- Galleom’s death animation doesn’t play when he’s the last fighter to die - 🟢
- Master Hand haystack needles are now fixed - 🟢 
- Marx Black Hole attack has been adjusted to eject the player and then spawn Marx back in - 🟢 
- Bosses controlled by a player are now put into maximum (10.0) AI intensity - 🟢 
- Damage multipliers within the code have been removed - 🟢 
- Bosses can now attack other bosses and correctly apply damage - 🟢
- Crashes on Rathalos have been addressed - 🟢 
- Crashes in team battle have been addressed - 🟢 
- Team battle stock issues have been addressed - 🟢 
- Stunned bosses now recover instantly
Galleom now has a new move on the left DPAD button - 🟢 
- Damage modules have been completely reworked so bosses no longer take damage on a preset value but rather what the character's damage output truly deals - 🟢 
- Master Hand and Crazy Hand now have a specific variation set of each other - 🟢 
- Dharkon and Galeem now have a specific variation set of each other - 🟢 
- WOL Master Hand no longer has spawning issues - 🟢 
- WOL Master Hand is now able to be controlled by the intended player most of the time - 🟢 
- WOL Spawn in issues addressed - 🟢 
- Flying bosses can now reach to edges of the stages rather than being within a restrictive pre-determined range - 🟢 
- Dharkon, Galeem, and Galleom’s rage values have been adjusted to 220 HP from 200 HP to not create Stamina battle issues.
Dracula’s transition HP value has been increased to 220 HP from 200 HP - 🟢 
- Mario's voice audio no longer plays during the result screen when a boss wins - 🟢 
- Secret maps are now available to be picked on the stage select screen - 🟢 
- Galleom and Ganon's WOL animations - 🟢
- Set Dharkon and Galeem to be chased by fighters. - 🟢
- More duet moves for Master Hand and Crazy Hand - 🟢 (Finder move was not possible and has been replaced with the duet beam attack)
- Set Dracula, Galleom, and Ganon to Hard Mode - 🟢
- Fix Crazy Hand's Chariot Index Finger - 🟢
- Marx AI Stub to properly work - 🟢
- Once Marx’ Black Hole Attack ends, become visible again - 🟢
- Stop Mario's Voice in the results screen - 🟢
- Bark attack on Master Hand is now in sync - 🟢
- Change Secret Stages to correctly load in 🟢
- Put images on Secret Stages - 🟢
- Major issue with Master Hand and Crazy Hand becoming uncontrollable - 🟢
- CSS Screen on Squad Strike is fixed - 🟢
- Squad Strike/Training mode spawn in system - 🟢
- Fixed the occasional Master Hand lose control - 🟢
- Princess Peach and Princess Daisy have passive healing abilities after acquiring a Smash Ball in order to compensate for their loss of final smash. This ability lasts until they lose a stock or the Smash Ball gets knocked out of them. - 🟢
- Final Touches - 🟢

Gutted features:

- Set Boss AI with Fighter AI level - ⚠️

Full release date: July 25, 10:00 AM PST.

🔴 = To Do
🟡 = More work to be done
🟢 = Good to go!
⚠️ = May not be possible
❗ = Debating on whether or not this should be added in

**Comment by cheetahsbdf** [comment]
Even with the finder move not working, could you make it still possible to shrink the stage?

**Comment by NemesisSSBU** [comment]
I would and I experimented with setting stage boundaries for the past couple days and they either didn't work at all or depleted everyone's stocks. So far the best bet would be somehow getting app::crazyhand::set_camera_range (found in Ghidra) to properly work.

**Comment by cheetahsbdf** [comment]
Alright. Thank you so much for your work! I am dying for the full release!!!

**Comment by cheetahsbdf** [comment]
For master and crazy hand, what you can do is set it to compare their level. if they are the same ai level, then they activate that AI level. if they aren't, a default level will be applied to both. this can be a moderate difficulty (ai level of 5). You can also make compact it to 3 different versions. If master hand is at ai level 1, 2, 3, 4 same as crazy hand between (1 and 4) They will both be at an easy difficulty internally at the same ai level. if they are levels 5 and 6, a medium difficulty will be applied to them at the same internal ai level. 7, 8, 9, puts both at a higher difficulty. You can try to make the code internally set them to the same "ai level" so no conflicts arise mid-fight. If Master Hand were to be set to difficulty 1 and Crazy Hand were to be set to difficulty 9, you could set them to a default difficulty such as prior. This seems like a good solution for the time being.

**Comment by NemesisSSBU** [comment]
That’s a really great idea! I was originally thinking of setting their AI level depending on who has the higher AI level, then setting it to that specific level. I’ll look into merging the two together in some sort of way.

**Comment by NemesisSSBU** [comment]
The mod is extremely close to being released. The only thing left is finding the actual AI value of the CPU fighter. Expect the full release to be out within a day or two.

**Comment by cheetahsbdf** [comment]
Nice!!!!!

**Comment by NemesisSSBU** [comment]
So uh, it's definitely taken longer than expected. Somehow I need to find the ai level, which I've been told it goes by ai_rank but I have to dig around some more. While doing this I luckily ran into a major Master Hand and Crazy Hand issue which is great since now I can patch that as the same time as working on the AI level.

**Comment by SwitchAdventurer** [comment]
So the release version come today or do we still have to wait a few days?

**Comment by NemesisSSBU** [comment]
I'm really hoping today but with how much reverse engineering sounds like is going to be involved to find the ai level, it may take a couple of extra days. But good news is once I figure it out, I can package the zip file and send it off as the trailer for the mod is already made and so is the GameBanana page.

**Comment by SwitchAdventurer** [comment]
Ok, thank you

**Comment by SwitchAdventurer** [comment]
But you finish to work for squad strike?

**Comment by SwitchAdventurer** [comment]
But before August will you be able to release the full version?

**Comment by NemesisSSBU** [comment]
Definitely. Some time between now and 3 days would be the release window.

**Comment by SwitchAdventurer** [comment]
Cool! So the mod is really close to release

**Comment by NemesisSSBU** [comment]
It’s unbelievably close. Only thing left that’s major is fixing the bosses disappearing when resetting positions in training mode and Squad Strike.

**Comment by SwitchAdventurer** [comment]
I hope you will manage to fix all the bugs

(PS: I was the one commenting at the boss trailer)

**Comment by cheetahsbdf** [comment]
I just saw this, yeah master hand sometimes looses control and sometimes the bark attack is sometimes not in sync when ai use it. (not sure if this is intentional, but the ai doesn't usually do any partner attacks. They do happen, but are quite uncommon)

**Comment by NemesisSSBU** [comment]
The occasional loss of control should be fixed now and the bark attack has been adjusted. The AI picks a number between 0 and 1000 every frame, then it picks another number between 0 and 1000 every frame, then once they end up being the same number and both Master Hand and Crazy Hand are facing the correct way, then it'll trigger the team attack. It's a lot of luck but for me it's the sweet spot between too little and too often.

**Comment by NemesisSSBU** [comment]
Alright, it's confirmed! Tomorrow at 10:00 AM. PST Playable Bosses will be fully released!

**Comment by SwitchAdventurer** [comment]
But you fixed the missing move on galleom?

**Comment by SwitchAdventurer** [comment]
Because you didn't put Galleom's missing move in the list of things that will be in the full version

**Comment by NemesisSSBU** [comment]
Yes, Galleom's move was fixed, I forgot to put it in the patch notes.

**Comment by SwitchAdventurer** [comment]
Oh, ok sorry

**Comment by SwitchAdventurer** [comment]
-5 minutes!

**Comment by NemesisSSBU** [comment]
[It's out!](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)

**Comment by SwitchAdventurer** [comment]
YEEESS IS OUTT!!!

**Comment by NemesisSSBU** [comment]
All issues that were listed in the issues section of this GitHub have been completely fixed! 🥳

**Comment by SwitchAdventurer** [comment]
But on crazy hand in the release with the duet move of lightining crazy hand can't not di moves :(
