### ISSUE TITLE
How To Uninstall?

### ISSUE THREAD

**Issue by CaptLixSkye** [NemesisSSBU/Playable_Bosses#27]
Says it all right there, is there a way to revert the changes made once the mod is installed? Love the mod just don't need it now

**Comment by NemesisSSBU** [comment]
Of course. Just head into your ultimate folder in the root of your SD Card and delete the “Bosses” mod folder. Next, head into your atmosphere folder, go to contents, then head into 01006A800016E000, then go into romfs —> skyline —> plugins —> then delete the libcomp_boss.nro file. You can also erase the other .nro files that came packaged with the mod if your other mods don’t require them.

**Comment by CaptLixSkye** [comment]
Hey! I did this and while the slots where the bosses were previously are now empty (no art and no text), the previously missing DLC characters have not returned to the CSS.

**Comment by NemesisSSBU** [comment]
Hm, that means the Bosses mod file was properly deleted but the libcomp_boss.nro file wasn’t. Also in the more recent versions of this mod DLC fighter’s shouldn’t be missing from the CSS so you might have an older libcomp_boss.bro file lurking within your plugins folder somewhere which is causing that issue

**Comment by CaptLixSkye** [comment]
I guess that's another point of confusion for me, I rolled back to 9.7 to see if the CSS changed at all and I'm still missing most of the DLC? Is there something else I have to do with CoolSonicKirby's remover onto the files for the mod? I've attatched a photo of my current CSS for reference as to my issue.
![unnamed-min](https://github.com/NemesisSSBU/Playable_Bosses/assets/139022294/d8860869-5a35-4ae0-9001-150762880e3b)

**Comment by CaptLixSkye** [comment]
I also paid for the CSS Redirector to remove the white box and that still didn't make any changes to the layout other than removing said box.

**Comment by NemesisSSBU** [comment]
This is very strange. No DLC should be missing and CoolSonicKirby’s plugin is automatic so that can’t be the issue. Can you take a screenshot of what your skyline mods plugin folder looks like?

**Comment by CaptLixSkye** [comment]
Yeah happily, here's what I'm working with.
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/139022294/46bbb1ca-4094-4324-a25d-5c56686985c8)

**Comment by NemesisSSBU** [comment]
Wow this is very puzzling. I just tried to replicate this issue on 2 modded switches and I can’t seem to come across this. Is it possible you have 2 skyline plugin folders? Perhaps an older one you no longer use?

**Comment by NemesisSSBU** [comment]
Oh wait, that’s looks like WinSCP. You can find the file by going to the top and clicking  on “Find Files”. Make sure your switch is idle and inside WinSCP, go to the File mask text field, enter “libcomp_boss” then press Start to start searching. This might take awhile but it should locate the file.

**Comment by CaptLixSkye** [comment]
So, libcomp_boss is under the plugins at /atmosphere/atmosphere/contents/01006A0016E000/romfs/skyline/plugins/ and I have a different plugins folder at /atmosphere/contents/01006A0016E000/romfs/skyline/plugins/, and both have different plugins inside of them.

Is this normal/how it is supposed to be? 
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/139022294/898b2585-94c4-41ae-b308-7bf545a25bf6)

**Comment by CaptLixSkye** [comment]
Okay, so I can now confidently say that the issue lies somewhere with libcomp_boss.nro . I've moved/functionally uninstalled all other mods besides the Bosses mod, and it works cleanly without libcomp_boss.nro, but the character screen is missing the DLC. However when I add that file into my plugins (the normal one, not the weird duplicate I had and have since deleted), the game won't launch.

**Comment by NemesisSSBU** [comment]
I see. You have an entire atmosphere folder inside of your regular atmosphere folder. This will create many unexpected hiccups. Deleting the duplicate atmosphere folder entirely would be the best course of action and be sure to move plugins you want found within the duplicate atmosphere folder into your main atmosphere folder’s environment. This might require a reboot of your switch since it’s fiddling with atmosphere.

**Comment by CaptLixSkye** [comment]
So! The second atmosphere folder is gone, and all the plugins have been migrated to the proper plugins folder. I have rebooted the Switch 4 times, 2 with libcomp_boss.nro and 2 without, and it's the same results as before where the game will not launch with the nro file and when it launches without, the layout remains unchanged from previous versions.

I'm honestly not quite sure what the issue is at this point? All other mods are uninstalled so there should be 0 conflicts other than potentially the one slot effects nro, but I removed that and tried as well to no avail.

Here's my current plugins folder once more if that's any help. I could also potentially send the crash reports?
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/139022294/18efa412-3416-4357-8920-6e0dbfa265c6)

**Comment by NemesisSSBU** [comment]
Please send the crash logs, I’m sorry about the mod causing this much trouble. Also, can you send a screenshot of your regular mods folder?

**Comment by CaptLixSkye** [comment]
No worries!! If anything I'm super grateful y'all are being this patient with the issues at hand :)

So, here we havee my root Ultimate folder, i have unused mods stored outside of the mods folder as shown.
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/139022294/f3d926f4-23cf-444b-bd64-f2bf380c14ae)
The mods folder itself however has nothing other than the Bosses mod inside of it, and as such is the only active mod rn.
![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/139022294/24af8afe-43e6-48ed-8956-07d11d6bf10d)

Then here's a few of the most recent crash logs. Hope these help!!
[01688962620_01006a800016e000.log](https://github.com/NemesisSSBU/Playable_Bosses/files/11997822/01688962620_01006a800016e000.log)
[01688962620_01006a800016e000.log](https://github.com/NemesisSSBU/Playable_Bosses/files/11997823/01688962620_01006a800016e000.log)

**Comment by NemesisSSBU** [comment]
Try deleting the Bosses mod folder and delete the libcomp_boss.nro file if you have it installed again. If the Bosses mod folder exists when trying to boot up the game without the libcomp_boss.nro file it tends to get a little bit weird and can crash, I’ve had that happen a few times.

If this also crashes, try booting up smash while holding the left shoulder button to boot up with no mods and see if that boots up with the CSS screen being fixed (it should since this will allow for Smash to boot without mods). This will indicate it’s not an atmosphere issue or something of the sort.

**Comment by CaptLixSkye** [comment]
So, deleting both the Bosses Mod folder and libcomp_boss.nro yielded the same results as before, the weird blanked out CSS.
![unnamed (1)](https://github.com/NemesisSSBU/Playable_Bosses/assets/139022294/66f0c537-beee-48e9-9572-ba67a0441919)

And then booting the game modless using left shoulder worked perfectly like normal (as it's supposed to I guess).
![unnamed (2)](https://github.com/NemesisSSBU/Playable_Bosses/assets/139022294/88cadfdb-816b-4e5b-b994-6850677e57ad)

**Comment by NemesisSSBU** [comment]
This is beyond strange, there’s definitely a .nro file being loaded. Is there a possibility of another libcomp_boss.nro file being hidden again? Try the WinSCP search again for that same file and if not, try to do a search for any .nro file, that way incase it was possibly renamed you can delete the out-of-place file.

**Comment by CaptLixSkye** [comment]
I may have fixed the problem!! I found an unnamed file that was simply ".nro" (sounds like it's out of a bad mid 2000s creepypasta but i'm not joking lol), and deleting it fixed my previous blanked out CSS, going to try re-installing the Boss mod now and hoping that this fixes the issues

**Comment by CaptLixSkye** [comment]
Sure enough!! It works perfectly now. That file was _**completely**_  hidden in normal view, and was only found through the Find action. But yeah, I'm seeing the full select roster now (wonderful composition btw, great arrangement on y'alls part).

Thank you so much for your help through this!!! It really means a lot that you were willing to stick with me through it :)
![unnamed (3)](https://github.com/NemesisSSBU/Playable_Bosses/assets/139022294/81ea36f6-50ba-4add-8025-7b10afb72d30)

**Comment by NemesisSSBU** [comment]
Awesome! I’m so glad to hear everything worked!

Those sneaky files can make modding a nightmare.
