### ISSUE TITLE
Question: Is it possible to make the bosses have Echo Slots or more skins?

### ISSUE THREAD

**Issue by MetalGearPearl** [NemesisSSBU/Playable_Bosses#28]
Hello again, this is not an issue, just a question, since I am using the Echo Slots mod, I would like to know if it is possible to make the game detect an additional skin for a boss, for example, I have a Yaldabaoth Over Ganon mod, but I don't know if it's possible to make that in addition to loading Ganon's c00 skin, also load the c01 skin where Yaldabaoth is located

**Comment by NemesisSSBU** [comment]
This is possible to add a skin slot by going into the lib.rs file and scrolling down to that character's PRC edits and adding in a new if statement that looks like this which sets it to 8 slots for example:

        if *hash == to_hash40("color_num") {
            *param.try_into_mut::<i8>().unwrap() = 8;
        }
