### ISSUE TITLE
Question: How do I add characters on the CSS?

### ISSUE THREAD

**Issue by MetalGearPearl** [NemesisSSBU/Playable_Bosses#30]
Hello! 
I have a question, your mod adds the bosses without physically modifying the ui_chara_db file and I would like to add characters to the CSS through the plugin, since I have reached the CSS Manager character limit and adding the characters from the plugin avoids that problem.
What code can I use to add the ones I like?

**Comment by cheetahsbdf** [comment]
This plugin does still use the ui_chara_db. it doesn't add any new slots, it just makes the invisible boss slots not invisible anymore.

**Comment by cheetahsbdf** [comment]
If you are talking about the css manager not allowing you to save after a certain amount of characters, there is a workaround.

**Comment by MetalGearPearl** [comment]
Oh, and what is it?

**Comment by cheetahsbdf** [comment]
you need both the prc editor and the manager

**Comment by cheetahsbdf** [comment]
Contact me on discord, I can fully assist you there. morbidlyabeast3745
