### ISSUE TITLE
Issue with all boss in traning mode

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#32]
Hi, i have another issue and is when  i go in traning mode with a boss and when i do L + R + A  (namely where I reset the positions of character) the bosses disappear and become invisible and do not moves

**Comment by SwitchAdventurer** [comment]
https://github.com/NemesisSSBU/Playable_Bosses/assets/137617315/89a7796e-4f93-403f-a135-e79a03f719cf

The problem is not only with Marx but with all

**Comment by NemesisSSBU** [comment]
That’s really good to know. I think I might have solution to this as well as squad strike and Princess Peach/Daisy. Most likely I can try to see if the fighter is holding an item and if not, the item will respawn.

**Comment by SwitchAdventurer** [comment]
But does that mean you're going to fix this problem?

**Comment by NemesisSSBU** [comment]
Of course. The 1.0.0 release will contain all fixes to the issues mentioned within every current issue found and far more. I made a list of what will be fixed in [this.](https://github.com/NemesisSSBU/Playable_Bosses/issues/25)

**Comment by SwitchAdventurer** [comment]
Thank you!

**Comment by NemesisSSBU** [comment]
Got a fix to work with almost all bosses with the exception of WOL Master Hand (only in training mode) and Dracula. They won't be able to do this since they're in standby mode in order for them to properly function.

The final thing left is to stress test the mod to its fullest extent.

**Comment by NemesisSSBU** [comment]
This is issue has been fixed in the [full release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0).
