### ISSUE TITLE
Ganon dies while doing Demon Rush

### ISSUE THREAD

**Issue by Minkachrgza-e** [NemesisSSBU/Playable_Bosses#34]
It seems Ganon gets stock loss when he gets out of screen while in move of Demon Rush, and he still gets back with no disappearing but when that happens the Ganon is counted as lost in battle. it happens both player and CPU.

**Comment by NemesisSSBU** [comment]
You’re right, I knew I forgot to put a range limit for his and Galleom’s death bounds. I’ll fix this ASAP

**Comment by NemesisSSBU** [comment]
The issue has been fixed in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0), thank you for reporting the issue.
