### ISSUE TITLE
When master hand do the move with rings its go down

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#36]
Yes, when master hand do the moves with rings orange its go to the Vs player  and not in the positions of were is master hand

**Comment by NemesisSSBU** [comment]
I was looking into that for awhile and I’ll need to look deeper into it. I think his rings might be attached to the stage and altering his already spawned in rings might be very difficult, like how Claude did it but he managed to spawn in separate rings from getting the actual item.lua_agent. Really impressive stuff that I’ll look into
