### ISSUE TITLE
Sometimes dracula's cloak freezes

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#37]
On Dracula if i do some moves her cloak go freeze for seconds And dracula doesn't leave him

**Comment by NemesisSSBU** [comment]
What move specifically does he freeze on?

**Comment by SwitchAdventurer** [comment]
With all i think

**Comment by SwitchAdventurer** [comment]
One second i will mand you a video

**Comment by SwitchAdventurer** [comment]
Uploading VID-20230727-WA0005.mp4…

**Comment by NemesisSSBU** [comment]
I don't think the video was attached.

**Comment by SwitchAdventurer** [comment]
Yes sorry one second is bugged

**Comment by SwitchAdventurer** [comment]
Uploading VID-20230727-WA0005.mp4…

**Comment by SwitchAdventurer** [comment]
Why? But on pc i can?

**Comment by NemesisSSBU** [comment]
I think you need to attach the video, wait about a minute then submit the comment.

**Comment by SwitchAdventurer** [comment]
But the move is the special move on and the special move with b

**Comment by SwitchAdventurer** [comment]
Uploading VID-20230727-WA0005.mp4…

**Comment by SwitchAdventurer** [comment]
https://github.com/NemesisSSBU/Playable_Bosses/assets/137617315/5c9f1aa2-9022-4ea4-8629-2fcc3366dd0a

**Comment by SwitchAdventurer** [comment]
Finally this is the video

**Comment by NemesisSSBU** [comment]
Oh that's intentional. His cape is programmed to close one move before his final move (as seen in the last attack, he closed his cape just before the last pillar spawned).

**Comment by SwitchAdventurer** [comment]
Ok, thank you and sorry
