### ISSUE TITLE
Master hand do the duet moves without crazy hand

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#38]
I was playing with my brother on the mod in classic mode: i'm ratalos and he master hand. But he got a metod to do the duet moves without master hand

**Comment by NemesisSSBU** [comment]
Just got a fix for it. The new update should be out in a few hours.

**Comment by SwitchAdventurer** [comment]
Well!

**Comment by NemesisSSBU** [comment]
Uploading it right now.

**Comment by NemesisSSBU** [comment]
[It's out](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)
