### ISSUE TITLE
Is missing a duet move

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#39]
I see is missing a duet move on master hand and crazy hand Where they narrow the map around fire

**Comment by NemesisSSBU** [comment]
That's the finder move which we looked into awhile ago and determined it wasn't possible to implement but maybe eventually we can tinker with it.

**Comment by SwitchAdventurer** [comment]
Oh ok sorry

**Comment by NemesisSSBU** [comment]
No it's totally fine to ask questions, don't be sorry.
