### ISSUE TITLE
I don't like this fact on dracula

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#40]
Hi, I don't like the fact that on dracula when he makes every attack it do automatically the special move Erupth fire and so it becomes impossible to beat dracula I want you to please fix it

**Comment by NemesisSSBU** [comment]
That’s his anger status. I can move his anger threshold to be after 100 HP to make him not so powerful.

**Comment by SwitchAdventurer** [comment]
So you fix this?

**Comment by SwitchAdventurer** [comment]
But i'm want you to toggle in every attack the Erupth Fire move

**Comment by SwitchAdventurer** [comment]
Because is impossibile to win versus dracula

**Comment by NemesisSSBU** [comment]
I can move it so he starts doing his fire pillars after 100 HP but he is very much so beatable. It might take some practice but he’s just a harder boss in general.

**Comment by SwitchAdventurer** [comment]
Ok for me is good

**Comment by NemesisSSBU** [comment]
Adjustment has been made in the [latest update](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)
