### ISSUE TITLE
CPU Ganon still does not use Laser Attack in anyway

### ISSUE THREAD

**Issue by Minkachrgza-e** [NemesisSSBU/Playable_Bosses#41]
You can let him use Laser Attack when you are using him as player, but he will not use that attack while in CPU in anyway.

**Comment by NemesisSSBU** [comment]
His CPU has the ability to but I think his probability of using it is fairly low (his probability of attacking is 1 in every 1000 and checking to see if another piece of code is equal to that same exact 1 in every 1000, so this comes to about a 0.000001 every frame.) This is far too low and thank you for pointing it out.

**Comment by NemesisSSBU** [comment]
Fixed in the [latest update](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)

**Comment by NemesisSSBU** [comment]
Wait I’m reopening this issue since I believe I misread the move that should be fixed. I did not yet fix the Ganon laser attack, that’ll come in the next bug patch.

**Comment by NemesisSSBU** [comment]
I figured out the issue. His laser attack triggers at a certain threshold of HP percentage, so now I'm setting his internal max HP higher.

**Comment by NemesisSSBU** [comment]
Now it's truly fixed in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)
