### ISSUE TITLE
When Galeem, Dharkon, Marx, master hand and crazy hand stay afk in the game they move little by little higher and higher

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#44]
So I don't know if it's a bug or not but when I go into the game with the flying bosses listed they always fly little by little higher by higher to go above the stage and if you want i can allo send to you a video

**Comment by NemesisSSBU** [comment]
I did notice this too, I figured it was because of my stick drift. I’ll look into this, thank you for confirming my suspicions.

**Comment by NemesisSSBU** [comment]
Just fixed in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)
