### ISSUE TITLE
one bug and one adjustment idea for Ganon

### ISSUE THREAD

**Issue by Minkachrgza-e** [NemesisSSBU/Playable_Bosses#46]
Bug: He kinda moves sideways while doing Demon Spin, instead of his position shouldn't move at all

Adjustment Idea: Ganon already and always Rage mode (idk what it is called) which he uses Laser atk and double thunder slash, like you adjusted Dracula having normal mode and rage mode (after him reaching 100% or more damages). is that also possible to adding this system to Ganon? which in Normal mode when he uses Thunder Slash it will be not doubled at all, and doesn't use Laser attack. and when he reaches rage mode, he stops using Single Thunder Slash and instead of that he uses Double Thunder Slash all time when he use Thunder Slash Attack, and starts using Laser Attack.

**Comment by NemesisSSBU** [comment]
Regarding the potential bug, I was looking into his spin and after watching his attack in regular game (I was watching [this YouTube video](https://m.youtube.com/watch?v=rlmfvalQYPI), skip to 8:30) and his spin attack does actually follow the player (also the player playing as him is able to do a similar thing by moving their joystick).

The improvement towards Ganon’s laser attack and thunder slash rage mode is actually an amazing idea, so good I immediately implemented it ASAP.

Thank you for reporting the issues and adjustments.

**Comment by Minkachrgza-e** [comment]
oh! I didn't knew that spin attack can come closer to player, thanks for telling that.

**Comment by NemesisSSBU** [comment]
These changes are now live in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0), thank you for suggesting the changes and checking in about a suspected bug.
