### ISSUE TITLE
ganonboss cause crash game when opponent die

### ISSUE THREAD

**Issue by RPTOR914** [NemesisSSBU/Playable_Bosses#48]
only happens with that boss, when an opponent dies, the game crash (only on ganonboss) thx

![image](https://github.com/NemesisSSBU/Playable_Bosses/assets/117567850/f8dfdcaa-cb67-44ca-84db-d9e76ead1095)

i have this mods

**Comment by NemesisSSBU** [comment]
I haven’t ran into the issue after some testing, but are you sure the mod you’re using is the same one released in this GitHub page and not Claude’s version of playable bosses?

I only say that because looking at your plugins folder, the boss nro file is smaller than usual and is called libboss.nro rather than libcomp_boss.nro and you have a css preserve plugin rather than css redirection.

**Comment by RPTOR914** [comment]
It's your version with another name, wait me pls

**Comment by NemesisSSBU** [comment]
Are you absolutely sure you downloaded this mod and it’s the latest version? If so, what opponent were you playing on and was it stamina mode or % battle?

**Comment by RPTOR914** [comment]
yes i downloader the latest version, and i tested on the stamina mode and % battle, crash for me (only for ganonboss), in your version i try to help you compiling the bosses for the missing moveset, or any another things

**Comment by NemesisSSBU** [comment]
Can you send an OBS recording (if you play on Ryujinx) of when the game crashes? I’ve tested about 40 different matches and haven’t crashed yet

**Comment by RPTOR914** [comment]
wait me i already recording in ryujinx (same on modded switch)

**Comment by RPTOR914** [comment]
only in 2 or more life in stock mode
https://drive.google.com/file/d/13kcOggpBVkdAxk_1xjMU9IYWZZzkfg0f/view?usp=sharing
sorry for lag and the link, github not allow me to send video, a fragment

**Comment by NemesisSSBU** [comment]
Thank you for uploading a video. I tried testing a few matches and I changed my language to Spanish to try and replicate this issue as close as possible. I tried on both Ryujinx and 2 Nintendo Switches yet didn’t crash on any. Is it possible the css preservation plugin is interfering with the mod?

**Comment by NemesisSSBU** [comment]
Very strange. I have those mods installed and some more, yet I haven't come across the issue. Is there any conflicting mods within your ultimate --> mods folder?

Here's an example of what I see on my end:

https://github.com/NemesisSSBU/Playable_Bosses/assets/88991848/ee7d04ae-34df-4c64-9512-a6e9cb936ef0

**Comment by RPTOR914** [comment]
i try to test with your mods now

sorry for the time but i are busy

**Comment by NemesisSSBU** [comment]
Is it possible you have a hidden .nro file in your plugins folder? I've seen things like this happen such as [within this issue](https://github.com/NemesisSSBU/Playable_Bosses/issues/27)

**Comment by NemesisSSBU** [comment]
Closed due to inactivity.
