### ISSUE TITLE
When dracula goes into phase two sometimes it spawns a dracula phase one cpu

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#49]
Sometimes, when dracula trasforma into phase 2, another dracula will spawn to help the phase two dracula fight. I tested if I was in control of it but instead it was a cpu and it moved by itself

**Comment by NemesisSSBU** [comment]
I figured I was playing it risky since if the game lags more than 2 frames during his transition a duplicate boss has a chance of spawning in. I’ll make it more lenient next update

**Comment by NemesisSSBU** [comment]
Thank you for reporting, this issue has been fixed in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0).
