### ISSUE TITLE
How to Increase the damage of Bosses

### ISSUE THREAD

**Issue by NineDracos** [NemesisSSBU/Playable_Bosses#50]
Hello, first off, I just wanna say that this mod is absolutely fantastic and is pretty much the only reason I'm still playing smash. Excellent work you guys have done.

That said I have a question; is there any way I could increase the damage of bosses, perhaps in the code itself? They do hit pretty hard, but I'd like them to hit at least a little bit harder, particular in spirit battles, where their damage doesn't match up at all to what opponents can do to them. I saw in one of the earlier builds that you had a damage increase for the bosses, hence why I asked this question.

Thanks in advance, and once again great job on this mod.

**Comment by NemesisSSBU** [comment]
I’m so glad to hear you’re enjoying the mod!

The way you would increase a bosses damage is by going into the code and inserting this one line of code to run every frame while in battle:
`AttackModule::set_power_mul(boss_boma, 1.2);`

The first place in the parameter is of course the battle object, the second is the damage multiplier on a 1.0 float scale.

I hope this helps!

**Comment by NineDracos** [comment]
Awesome. Inserted the line you suggested and it worked like a charm. Had to lower the damage output tho, I believe I made the bosses hit a little _too_ hard... hahahahaha.

Final question I have though regarding the source code. Unfortunately Ganon's demon rush will still insta-kill him if he uses it while either controlled by the player or CPU, as it seems the source code contents doesn't include the fix you gave for that issue of one of the recent updates. Can you give me the code line needed to fix that issue? Thank you for responding to my initial question by the way.

**Comment by An-Untitled-Developer** [comment]
> I’m so glad to hear you’re enjoying the mod!
> 
> The way you would increase a bosses damage is by going into the code and inserting this one line of code to run every frame while in battle: `AttackModule::set_power_mul(boss_boma, 1.2);`
> 
> The first place in the parameter is of course the battle object, the second is the damage multiplier on a 1.0 float scale.
> 
> I hope this helps!

Where do you put the damage multiplier,
