### ISSUE TITLE
Source code version of Ganon still has demon rush death issue

### ISSUE THREAD

**Issue by NineDracos** [NemesisSSBU/Playable_Bosses#51]
After playing around with the source code edits, everything works great, except for Ganon himself. He still suffers from the issue where performing his demon rush special will cause him to suffer an off-screen death. Is there any way possible you could share the line of code needed to fix this issue that the latest versions of this mod has?

My apologies if my question sounds confusing.

**Comment by NemesisSSBU** [comment]
That's strange. The source code does have the boundary limits and they can be located here: https://github.com/NemesisSSBU/Playable_Bosses/blob/f7e309a15b68b0441f57d19a3df0a589519ea0bd/src/ganon/mod.rs#L257-L413

Your question is totally reasonable since this mod is very delicate at times lol.

**Comment by NineDracos** [comment]
Oh, ok thanks for providing that. I'll try inserting that code and see if it works. 
Thank you for the help, and once again, excellent job on this mod, it has truly changed smash forever in a positive way for me.

**Comment by NemesisSSBU** [comment]
Always glad to help! Your kind words about the mod mean a lot to us. Enjoy the game and the new possibilities the mod brings!

**Comment by NemesisSSBU** [comment]
Wait! I think I know what happened. You might’ve accidentally downloaded the source code linked to 1.0.0 rather than the current version. [Here’s the most up-to-date source code](https://github.com/NemesisSSBU/Playable_Bosses)

**Comment by NineDracos** [comment]
Ah ok, thank you! I'll try out that code later when I'm not busy. You've been a great help to me in figuring out the problems I had.

Looking forward to all future updates you guys have in store for this mod. Keep up the great work!
