### ISSUE TITLE
infinite loading ssbu ultimate screen (with ryujinx)

### ISSUE THREAD

**Issue by Valsorx** [NemesisSSBU/Playable_Bosses#58]
The mod isn't working and i tried following the steps over and over again but it still doesn't work and keeps on infinitly loading i'm also using ryujinx idk if that is the problem but im pretty sure it isnt because i have seen alot of other people use it if anyone knows how to fix these please help me

**Comment by NemesisSSBU** [comment]
Hey there,

Sorry for not responding earlier but usually issues are discussed on the Game Banana page. But as for the infinite loading screen, are you sure you’re using Smashline 2.0 and now the regular Smashline? Also are you on Smash version 13.0.2?

**Comment by Valsorx** [comment]
Hey thanks for reaching out to me but yes those were the exact reason why I
was experiencing those issues I reached out to you on YouTube also and you
responded so I have resolved the issue
