### ISSUE TITLE
Make bosses respawn into the match in VS mode

### ISSUE THREAD

**Issue by timmehz** [NemesisSSBU/Playable_Bosses#6]
Could you make bosses respawn into the VS match once killed

Currently bosses rather do 2 things it seems:
1. respawn when killed but keep on dying over and over again non stop
2. does not respawn in at all

I know making bosses respawn is not normal but it would be better if they are able to respawn and still can be controlled in VS mode.

**Comment by NemesisSSBU** [comment]
We were actually experimenting with making it so bosses can respawn or not based on the users configurations.

The bosses dying over and over again is a bug that we thought we got rid of awhile ago, unfortunate it made a comeback, we'll be looking into this.

We hope to implement this feature soon as it seems pretty cool.

**Comment by NemesisSSBU** [comment]
Bosses trying to respawn over and over again has now been fixed in the [latest release](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/0.9.9.1)! Thank you for reporting the issue!
