### ISSUE TITLE
My game crash

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#60]
Sorry for post this issue but when I put the mod on my switch ssbu crash, why?

**Comment by NemesisSSBU** [comment]
Hi there,

Is it possible for you to show what's in your atmosphere folder as well as your ultimate mods folder?

**Comment by SwitchAdventurer** [comment]
Oh Hi ty for rispond to me but I need to say sorry because that isn't an error of your mods but an error of my mods on switch.  The problem was that in my css manager I didn't have the gigabowser hidden slot.

**Comment by NemesisSSBU** [comment]
Awesome! I'm glad you figured it out and I'll be marking this as resolved thank you for telling me and happy modding!
