### ISSUE TITLE
Master Hand and Crazy Hand should teleport in the middle of the stage for Stage Shock.

### ISSUE THREAD

**Issue by An-Untitled-Developer** [NemesisSSBU/Playable_Bosses#62]
### Enhancement

When using Stage Shock (Jump Button on Master Hand), they should be teleported to the middle to not cause a severe disjoint. 
_You almost always can't center Stage Shock, or you do the team attack just a bit too high or too low._

**Comment by NemesisSSBU** [comment]
Hmm, this should already be the case mostly, or more so when the button is pressed they should only be able to be utilized when a certain position above the stage. I'll be sure to look into it, thank you.

**Comment by An-Untitled-Developer** [comment]
The range is decently big meaning it's possible to do it. And ye are welcome :P

**Comment by NemesisSSBU** [comment]
Good news this issue has been fixed in the latest release (2.0.5). Thank you for telling me.

**Comment by An-Untitled-Developer** [comment]
yayayayya

**Comment by An-Untitled-Developer** [comment]
ye are awesome suace
