### ISSUE TITLE
Chakram still get's snapped to the middle of the stage (although rarely)

### ISSUE THREAD

**Issue by An-Untitled-Developer** [NemesisSSBU/Playable_Bosses#64]
Haven't gotten this bug when I was recording, but does happen if master hand doesn't have a target at the start of the match.

**Comment by NemesisSSBU** [comment]
Hey there, sorry this issue wasn't able to be completely replicated therefore it isn't a major issue. And we will keep this in mind going forward and if it becomes a larger issue, we will dig much deeper into this. Thank you for informing us.
