### ISSUE TITLE
The playable bosses mod needed to be updated for the smash version 13.0.3?

### ISSUE THREAD

**Issue by SwitchAdventurer** [NemesisSSBU/Playable_Bosses#65]
Hi, I was asking this question if this mod was compatible with smash version 13.0.3 or not, like you need to do an update for this mod to work with the latest version of smash? Ty and have a good day!

**Comment by SwitchAdventurer** [comment]
Oh ok, tysm :)

**Comment by NemesisSSBU** [comment]
Good news! We just updated to 13.0.3 happy modding!
