### ISSUE TITLE
📝 Documentation - CSK Collection Dependency + Suyu installation

### ISSUE THREAD

**Issue by Rikj000** [NemesisSSBU/Playable_Bosses#66]
I've noticed that the Github documentation currently is lacking references to:
- [x] Dependency: [The CSK Collection](https://gamebanana.com/mods/499008) + configuration flag requirements
- [x] Guide: [ARCropolis Mods using Yuzu/Suyu Emulator](https://gamebanana.com/tuts/14688)

It would be nice if these could be added.

**Comment by NemesisSSBU** [comment]
Thank you for reminding me! I'll be sure to add it right now.

**Comment by Rikj000** [comment]
The Yuzu/Suyu guide has been privatized,   
and I've noticed that the guide you linked does not describe emulator setup.

However, here is the latest internet archived version of the guide I initially posted:
https://web.archive.org/web/20240716095431/https://gamebanana.com/tuts/14688
