### ISSUE TITLE
🐞 Bug - Peach + Daisy game crash

### ISSUE THREAD

**Issue by Rikj000** [NemesisSSBU/Playable_Bosses#67]
## Issue Description
When attempting to fight with or against Peach / Daisy,   
it causes the game to crash during the battle loading screen.

This issue occurs both on:
- Native hardware
- Emulator

## Environment
| Software | Version |
| --- | --- |
| [Super Smash Bros. Ultimate](https://www.ssbwiki.com/List_of_updates_(SSBU)) | [v13.0.3](https://www.ssbwiki.com/List_of_updates_(SSBU)#13.0.3) |
| [Horizon](https://switchbrew.org/wiki/System_Versions) | [v19.0.0](https://switchbrew.org/wiki/19.0.0) |
| [Atmosphere](https://github.com/Atmosphere-NX/Atmosphere) | [v1.8.0-pre-c6014b533](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.8.0-prerelease) |
| [Suyu](https://git.suyu.dev/suyu/suyu/) | [v0.0.4](https://aur.archlinux.org/packages/suyu-bin) |
| [ARCropolis](https://github.com/Raytwo/ARCropolis) | [v4.0.6](https://github.com/Raytwo/ARCropolis/releases/tag/v4.0.6) |
| [Skyline](https://github.com/skyline-dev/skyline) | [v2024.02.25-beta](https://github.com/skyline-dev/skyline/releases/tag/beta) |
| [NRO Hook Plugin](https://github.com/ultimate-research/nro-hook-plugin) | [v0.4.0](https://github.com/ultimate-research/nro-hook-plugin/releases/tag/v0.4.0) |
| [Smashline 2](https://github.com/HDR-Development/smashline) | [v1.5.1](https://github.com/HDR-Development/smashline/releases/tag/v1.5.1) |
| [The CSK Collection](https://gamebanana.com/mods/499008) | [v4.0.0](https://gamebanana.com/mods/download/499008) |
| [Playable Bosses](https://github.com/NemesisSSBU/Playable_Bosses) | [v2.0.5](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0) |

**Comment by battleforce404** [comment]
It crashed the game when I try to fight the golden peach on WOL also

Playing on switch

**Comment by NemesisSSBU** [comment]
Thank you. This issue has now been fixed in the latest update.

**Comment by Rikj000** [comment]
Tested on native hardware + emulator,   
and confirmed as resolved with [Playable Bosses](https://github.com/NemesisSSBU/Playable_Bosses) @ [v2.0.6](https://github.com/NemesisSSBU/Playable_Bosses/releases/tag/1.0.0)! :tada: 

Thank you @NemesisSSBU! :relaxed:

**Comment by battleforce404** [comment]
The bug still happens

**Comment by battleforce404** [comment]
I'm playing with the mod on switch
